### ISSUE TITLE
Studio Friday breaks with AgentScope v1.0.14 JSONSession API change

### ISSUE THREAD

**Issue by zhijianma** [agentscope-ai/agentscope-studio#114]
**Bug description**
After upgrading AgentScope from v1.0.13 to v1.0.14, running Studio Friday throws:

```
File "/app/dist/app/friday/main.py", line 164, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/dist/app/friday/main.py", line 141, in main
    session = JSONSession(
TypeError: JSONSession.__init__() got an unexpected keyword argument 'session_id'
File not found: /app/data/AgentScope-Studio/Friday/session.json
```

AgentScope v1.0.14 changed the JSONSession API and removed support for the 'session_id' argument. This causes Studio Friday to fail on startup.

**Steps to reproduce**
1. Upgrade AgentScope to v1.0.14 in agentscope-ai/agentscope-studio.
2. Start Friday.
3. Observe the TypeError above.

**Expected behavior**
Studio Friday should start normally and support both old and new versions of AgentScope.

**Additional context**
- Studio Friday needs to adapt to the new JSONSession interface and remain compatible with previous AgentScope versions.
- Consider preinstalling AgentScope full version in docker images.
- See https://agentscope-ai.github.io/agentscope-studio/ for documentation and commit conventions.
